# Generated by Django 4.2.5 on 2023-09-21 17:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=127,
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.media"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "db_table": "job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestKit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("score", models.FloatField()),
                ("box", models.JSONField()),
                ("is_ok", models.BooleanField(default=True)),
                (
                    "feedback_label",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="test_kits",
                        to="detect.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Kit",
                "verbose_name_plural": "Test Kits",
                "db_table": "test_kit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "version",
                    models.PositiveSmallIntegerField(default=1, editable=False),
                ),
                ("description", models.TextField(blank=True)),
                ("class_to_label", models.JSONField(default=dict)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.media"
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Version",
                "verbose_name_plural": "Model Versions",
                "db_table": "model_version",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="model_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="detect.modelversion"
            ),
        ),
    ]
