# Generated by Django 4.2.5 on 2023-09-22 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_media_utag"),
        ("detect", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="modelversion",
            unique_together={("model", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="testkit",
            unique_together={("job", "box")},
        ),
    ]
