# Generated by Django 4.2.5 on 2023-09-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("detect", "0002_alter_modelversion_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="model_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="detect.modelversion",
            ),
        ),
    ]
