# Generated by Django 4.2.5 on 2023-09-22 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("detect", "0004_modelversion_local_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modelversion",
            old_name="local_path",
            new_name="local_model_path",
        ),
    ]
