# Generated by Django 4.2.5 on 2023-09-24 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("detect", "0005_rename_local_path_modelversion_local_model_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testkit",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="detect.job",
            ),
        ),
    ]
