# Generated by Django 4.2.5 on 2023-10-11 10:16

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import uuid


def obj_to_list(apps, schema_editor):
    ModelVersion = apps.get_model("detect", "ModelVersion")
    for mv in ModelVersion.objects.all():
        items = []
        for k, v in mv.class_to_label.items():
            items.append({"class": k, "label": v})
        mv.class_to_label = items
        mv.save()


class Migration(migrations.Migration):
    dependencies = [
        ("detect", "0006_alter_testkit_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestKitGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("class_to_label", django_jsonform.models.fields.JSONField()),
                ("uid", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Test Kit Group",
                "verbose_name_plural": "Test Kit Groups",
                "db_table": "test_kit_group",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="class_to_label",
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AddField(
            model_name="job",
            name="test_kit_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="detect.testkitgroup",
            ),
        ),
        migrations.RunPython(obj_to_list),
    ]
