# Generated by Django 4.2.5 on 2023-10-30 12:03

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("detect", "0007_testkitgroup_alter_modelversion_class_to_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testkitgroup",
            name="activation_alias",
            field=django_jsonform.models.fields.JSONField(blank=True, default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="modelversion",
            name="class_to_label",
            field=django_jsonform.models.fields.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="testkitgroup",
            name="class_to_label",
            field=django_jsonform.models.fields.JSONField(blank=True),
        ),
    ]
