# Generated by Django 4.2.5 on 2023-12-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("detect", "0008_testkitgroup_activation_alias_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testkitgroup",
            options={
                "ordering": ["child_sequence", "-created_at"],
                "verbose_name": "Test Kit Group",
                "verbose_name_plural": "Test Kit Groups",
            },
        ),
        migrations.AddField(
            model_name="testkitgroup",
            name="child_sequence",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="testkitgroup",
            name="parent_kit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="child_kits",
                to="detect.testkitgroup",
            ),
        ),
    ]
