# Generated by Django 4.2.5 on 2023-09-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="utag",
            field=models.CharField(default="test", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
